export type Mood = "night" | "ember" | "cold" | "haze" | "pulse";
export type ScaleName = "minor" | "major" | "dorian";
export type VideoTheme = "orbit" | "rain" | "shatter" | "scan" | "bloom" | "grid" | "pulse" | "haze";
export type Section = "intro" | "verse" | "pre" | "chorus" | "bridge" | "outro";

export type LyricLine = {
  bar: number;
  text: string;
};

export type Song = {
  id: string;
  no: number;
  title: string;
  bpm: number;
  bars: number;
  tonic: number;
  scale: ScaleName;
  energy: number;
  brightness: number;
  swing: number;
  mood: Mood;
  theme: VideoTheme;
  cover: string;
  verseChords: number[];
  chorusChords: number[];
  verseHook: number[];
  chorusHook: number[];
  lyrics: LyricLine[];
};

export const ARTIST = {
  name: "LINNEIRO",
  album: "AFTERGLOW",
  year: 2026,
  released: "September 19, 2026",
  genre: "Pop",
  origin: "20 years old · 1.64m · 70kg · one voice on every track",
  portrait: "/artist/source-square.jpg",
  hero: "/artist/hero.jpg",
  albumCover: "/artist/album.jpg",
  avatar: "/artist/avatar.png",
} as const;

const REST = -99;

export const SONGS: Song[] = [
  {
    id: "afterglow",
    no: 1,
    title: "Afterglow",
    bpm: 118,
    bars: 52,
    tonic: 48,
    scale: "minor",
    energy: 0.72,
    brightness: 0.55,
    swing: 0.04,
    mood: "ember",
    theme: "bloom",
    cover: "/covers/01.jpg",
    verseChords: [0, 5, 3, 4],
    chorusChords: [5, 3, 0, 4],
    verseHook: [0, REST, 0, 2, 3, 3, 2, 0, 0, REST, 2, 3, 5, 3, 2, REST],
    chorusHook: [4, 4, 5, 7, 7, REST, 5, 4, 2, 2, 0, 0, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "The city holds its breath tonight" },
      { bar: 6, text: "Streetlights humming through the glass" },
      { bar: 8, text: "I still see you in the leftover light" },
      { bar: 10, text: "A photograph that wouldn't last" },
      { bar: 12, text: "Don't ask me to forget the heat" },
      { bar: 14, text: "The way the evening learned our names" },
      { bar: 16, text: "We were brighter in the afterglow" },
      { bar: 18, text: "Burning quiet where the night don't go" },
      { bar: 20, text: "If the morning tries to take us home" },
      { bar: 22, text: "I'll keep you in the afterglow" },
      { bar: 24, text: "Your jacket on the hotel chair" },
      { bar: 26, text: "A song we never learned to sing" },
      { bar: 28, text: "I talk to shadows like you're there" },
      { bar: 30, text: "And every silence has your name in it" },
      { bar: 32, text: "We were brighter in the afterglow" },
      { bar: 34, text: "Burning quiet where the night don't go" },
      { bar: 36, text: "If the morning tries to take us home" },
      { bar: 38, text: "I'll keep you in the afterglow" },
      { bar: 40, text: "Hold the dark a little longer" },
      { bar: 42, text: "Let the embers learn to stay" },
      { bar: 44, text: "We were brighter in the afterglow" },
      { bar: 46, text: "Don't you let the morning know" },
      { bar: 48, text: "I'll keep you in the afterglow" },
      { bar: 50, text: "I'll keep you in the afterglow" },
    ],
  },
  {
    id: "midnight-frequency",
    no: 2,
    title: "Midnight Frequency",
    bpm: 102,
    bars: 48,
    tonic: 45,
    scale: "minor",
    energy: 0.55,
    brightness: 0.35,
    swing: 0.06,
    mood: "night",
    theme: "scan",
    cover: "/covers/02.jpg",
    verseChords: [0, 6, 3, 4],
    chorusChords: [0, 3, 5, 4],
    verseHook: [0, 0, REST, 2, 3, REST, 5, 3, 2, 2, REST, 0, 3, 2, 0, REST],
    chorusHook: [7, 5, 4, 5, 7, REST, 4, 2, 0, 0, 2, 3, 5, 4, 0, REST],
    lyrics: [
      { bar: 4, text: "Tuned the dial until it found you" },
      { bar: 6, text: "Static kissing through the wire" },
      { bar: 8, text: "Every late-night station sounds like" },
      { bar: 10, text: "A room we never quite left behind" },
      { bar: 12, text: "Say my name across the distance" },
      { bar: 14, text: "I'll be listening on the line" },
      { bar: 16, text: "You're a midnight frequency" },
      { bar: 18, text: "Coming in when the world goes quiet" },
      { bar: 20, text: "If the signal starts to leave me" },
      { bar: 22, text: "I'll keep turning through the night" },
      { bar: 24, text: "Hotel radios and rain on glass" },
      { bar: 26, text: "I collect the songs you used to play" },
      { bar: 28, text: "There's a ghost inside the broadcast" },
      { bar: 30, text: "And it knows the words I never say" },
      { bar: 32, text: "You're a midnight frequency" },
      { bar: 34, text: "Coming in when the world goes quiet" },
      { bar: 36, text: "If the signal starts to leave me" },
      { bar: 38, text: "I'll keep turning through the night" },
      { bar: 40, text: "Don't you fade, don't you fade" },
      { bar: 42, text: "Stay between the stations" },
      { bar: 44, text: "Midnight frequency" },
      { bar: 46, text: "Stay with me" },
    ],
  },
  {
    id: "glass-heart",
    no: 3,
    title: "Glass Heart",
    bpm: 96,
    bars: 48,
    tonic: 50,
    scale: "minor",
    energy: 0.4,
    brightness: 0.42,
    swing: 0.02,
    mood: "haze",
    theme: "shatter",
    cover: "/covers/03.jpg",
    verseChords: [0, 3, 5, 4],
    chorusChords: [5, 0, 3, 4],
    verseHook: [4, REST, 2, 0, 0, REST, 2, 3, 4, 4, REST, 5, 3, 2, 0, REST],
    chorusHook: [7, 7, 5, 4, 4, REST, 2, 0, 3, 3, 2, 0, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "You held me like a secret" },
      { bar: 6, text: "Too careful and too loud" },
      { bar: 8, text: "I learned the sound of leaving" },
      { bar: 10, text: "Before you said it out loud" },
      { bar: 12, text: "Every promise has an edge" },
      { bar: 14, text: "Every tenderness a crack" },
      { bar: 16, text: "I gave you a glass heart" },
      { bar: 18, text: "You looked surprised when it broke" },
      { bar: 20, text: "Now the light comes through the pieces" },
      { bar: 22, text: "That's a kind of hope" },
      { bar: 24, text: "I swept the floor at midnight" },
      { bar: 26, text: "Kept a shard inside my coat" },
      { bar: 28, text: "If I bleed a little later" },
      { bar: 30, text: "At least I'll know I felt it most" },
      { bar: 32, text: "I gave you a glass heart" },
      { bar: 34, text: "You looked surprised when it broke" },
      { bar: 36, text: "Now the light comes through the pieces" },
      { bar: 38, text: "That's a kind of hope" },
      { bar: 40, text: "Don't you gather what you shattered" },
      { bar: 42, text: "Let it glitter, let it go" },
      { bar: 44, text: "Glass heart, glass heart" },
      { bar: 46, text: "Still it shows" },
    ],
  },
  {
    id: "neon-saints",
    no: 4,
    title: "Neon Saints",
    bpm: 124,
    bars: 48,
    tonic: 53,
    scale: "dorian",
    energy: 0.88,
    brightness: 0.6,
    swing: 0.0,
    mood: "pulse",
    theme: "grid",
    cover: "/covers/04.jpg",
    verseChords: [0, 6, 3, 4],
    chorusChords: [0, 4, 6, 3],
    verseHook: [0, 0, 3, 5, 7, 7, 5, 3, 0, 0, 3, 5, 4, 4, 2, REST],
    chorusHook: [7, 7, 7, 4, 4, REST, 6, 4, 0, 0, 2, 4, 7, 5, 4, REST],
    lyrics: [
      { bar: 4, text: "We don't pray, we just keep dancing" },
      { bar: 6, text: "Halos made of traffic light" },
      { bar: 8, text: "Every sinner on this corner" },
      { bar: 10, text: "Looks like heaven after midnight" },
      { bar: 12, text: "Raise a glass to getting older" },
      { bar: 14, text: "Raise a hand and miss the beat" },
      { bar: 16, text: "Neon saints, neon saints" },
      { bar: 18, text: "Bless the ones who stay too late" },
      { bar: 20, text: "If the morning wants a martyr" },
      { bar: 22, text: "We already burned the page" },
      { bar: 24, text: "Your red dress is a cathedral" },
      { bar: 26, text: "My bad luck is just a hymn" },
      { bar: 28, text: "Kiss me like you mean the ending" },
      { bar: 30, text: "Sing it like a last amen" },
      { bar: 32, text: "Neon saints, neon saints" },
      { bar: 34, text: "Bless the ones who stay too late" },
      { bar: 36, text: "If the morning wants a martyr" },
      { bar: 38, text: "We already burned the page" },
      { bar: 40, text: "Hallelujah in the alley" },
      { bar: 42, text: "Nothing holy, still we shine" },
      { bar: 44, text: "Neon saints" },
      { bar: 46, text: "Neon saints" },
    ],
  },
  {
    id: "dont-call-it-love",
    no: 5,
    title: "Don't Call It Love",
    bpm: 110,
    bars: 48,
    tonic: 52,
    scale: "minor",
    energy: 0.6,
    brightness: 0.48,
    swing: 0.05,
    mood: "ember",
    theme: "orbit",
    cover: "/covers/05.jpg",
    verseChords: [0, 4, 5, 3],
    chorusChords: [5, 4, 0, 3],
    verseHook: [2, 2, 0, REST, 3, 3, 2, 0, 5, 4, 2, REST, 0, 0, REST, REST],
    chorusHook: [4, 5, 7, 7, 5, 4, 2, 0, 4, 4, 2, 0, 5, 3, 0, REST],
    lyrics: [
      { bar: 4, text: "You say forever like a rumor" },
      { bar: 6, text: "Soft enough to pass for true" },
      { bar: 8, text: "I keep my coat on in your kitchen" },
      { bar: 10, text: "I already know the move" },
      { bar: 12, text: "Call it weather, call it timing" },
      { bar: 14, text: "Call it anything but this" },
      { bar: 16, text: "Don't call it love, don't call it love" },
      { bar: 18, text: "If you're leaving in the morning" },
      { bar: 20, text: "Don't call it love, don't call it love" },
      { bar: 22, text: "Just because it felt like falling" },
      { bar: 24, text: "We were good at almost meaning it" },
      { bar: 26, text: "Good at burning through a night" },
      { bar: 28, text: "I don't need another sermon" },
      { bar: 30, text: "I just need you not to lie" },
      { bar: 32, text: "Don't call it love, don't call it love" },
      { bar: 34, text: "If you're leaving in the morning" },
      { bar: 36, text: "Don't call it love, don't call it love" },
      { bar: 38, text: "Just because it felt like falling" },
      { bar: 40, text: "Keep the heat, keep the hush" },
      { bar: 42, text: "Leave the word out of your mouth" },
      { bar: 44, text: "Don't call it love" },
      { bar: 46, text: "Let it burn without a name" },
    ],
  },
  {
    id: "runaway-lights",
    no: 6,
    title: "Runaway Lights",
    bpm: 126,
    bars: 48,
    tonic: 55,
    scale: "minor",
    energy: 0.85,
    brightness: 0.58,
    swing: 0.0,
    mood: "cold",
    theme: "rain",
    cover: "/covers/06.jpg",
    verseChords: [0, 6, 4, 5],
    chorusChords: [0, 3, 6, 4],
    verseHook: [0, 0, 4, 5, 7, REST, 5, 4, 0, 0, 2, 4, 5, 4, 0, REST],
    chorusHook: [7, 7, 5, 4, 7, 7, 4, 2, 0, 0, 2, 4, 7, 5, 0, REST],
    lyrics: [
      { bar: 4, text: "Packed the night into the backseat" },
      { bar: 6, text: "Left the city like a bruise" },
      { bar: 8, text: "Every exit said your name in" },
      { bar: 10, text: "Red and white I couldn't use" },
      { bar: 12, text: "Tell the dark we're only passing" },
      { bar: 14, text: "Tell the map to look away" },
      { bar: 16, text: "Runaway lights, runaway lights" },
      { bar: 18, text: "Chase me out of my old life" },
      { bar: 20, text: "If the highway wants a reason" },
      { bar: 22, text: "I was never good at goodbye" },
      { bar: 24, text: "Coffee cooling on the dashboard" },
      { bar: 26, text: "Your song dying in the tape" },
      { bar: 28, text: "I don't know the town we're headed" },
      { bar: 30, text: "I just know I can't stay late" },
      { bar: 32, text: "Runaway lights, runaway lights" },
      { bar: 34, text: "Chase me out of my old life" },
      { bar: 36, text: "If the highway wants a reason" },
      { bar: 38, text: "I was never good at goodbye" },
      { bar: 40, text: "Don't look back, the glass is burning" },
      { bar: 42, text: "Every mile undoes a lie" },
      { bar: 44, text: "Runaway lights" },
      { bar: 46, text: "Keep me flying" },
    ],
  },
  {
    id: "slow-burn",
    no: 7,
    title: "Slow Burn",
    bpm: 84,
    bars: 44,
    tonic: 48,
    scale: "major",
    energy: 0.28,
    brightness: 0.62,
    swing: 0.08,
    mood: "ember",
    theme: "haze",
    cover: "/covers/07.jpg",
    verseChords: [0, 4, 5, 3],
    chorusChords: [5, 3, 0, 4],
    verseHook: [4, REST, 2, 0, REST, 4, 5, 4, 2, REST, 0, 2, 4, 2, 0, REST],
    chorusHook: [4, 4, 5, 7, 4, REST, 2, 0, 5, 5, 4, 2, 0, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "No fireworks, no sirens" },
      { bar: 6, text: "Just a match against the dark" },
      { bar: 8, text: "You don't rush a thing worth keeping" },
      { bar: 10, text: "You just stay and leave a mark" },
      { bar: 12, text: "Take the long way through the evening" },
      { bar: 14, text: "Let the quiet do the work" },
      { bar: 16, text: "This is a slow burn, baby" },
      { bar: 18, text: "Not a blaze to survive" },
      { bar: 20, text: "If it takes the whole night" },
      { bar: 22, text: "That's alright, that's alright" },
      { bar: 24, text: "Your hand finds mine like a rumor" },
      { bar: 26, text: "That the world already knew" },
      { bar: 28, text: "I don't need a grand confession" },
      { bar: 30, text: "I just need the morning with you" },
      { bar: 32, text: "This is a slow burn, baby" },
      { bar: 34, text: "Not a blaze to survive" },
      { bar: 36, text: "If it takes the whole night" },
      { bar: 38, text: "That's alright, that's alright" },
      { bar: 40, text: "Stay, stay, let it smolder" },
      { bar: 42, text: "Slow burn, hold me closer" },
    ],
  },
  {
    id: "city-of-ghosts",
    no: 8,
    title: "City of Ghosts",
    bpm: 90,
    bars: 48,
    tonic: 51,
    scale: "minor",
    energy: 0.35,
    brightness: 0.3,
    swing: 0.03,
    mood: "night",
    theme: "rain",
    cover: "/covers/08.jpg",
    verseChords: [0, 5, 6, 4],
    chorusChords: [0, 3, 5, 6],
    verseHook: [0, REST, 2, 3, REST, 5, 3, 2, 0, REST, 3, 5, 7, 5, 3, REST],
    chorusHook: [5, 5, 3, 0, 7, 5, 3, 0, 4, 4, 2, 0, 5, 3, 0, REST],
    lyrics: [
      { bar: 4, text: "Empty cafés keep our table" },
      { bar: 6, text: "Windows breathing on the street" },
      { bar: 8, text: "I walk the blocks we used to waste" },
      { bar: 10, text: "And every doorway wears your heat" },
      { bar: 12, text: "The city learned to speak in echoes" },
      { bar: 14, text: "I answer like you're still around" },
      { bar: 16, text: "This is a city of ghosts" },
      { bar: 18, text: "And I'm the last one going home" },
      { bar: 20, text: "If I turn the corner slowly" },
      { bar: 22, text: "Maybe you'll be there in gold" },
      { bar: 24, text: "Rain redraws the map of almost" },
      { bar: 26, text: "Neon spelling what we lost" },
      { bar: 28, text: "I keep your key out of a habit" },
      { bar: 30, text: "Not a hope, not anymore, just cost" },
      { bar: 32, text: "This is a city of ghosts" },
      { bar: 34, text: "And I'm the last one going home" },
      { bar: 36, text: "If I turn the corner slowly" },
      { bar: 38, text: "Maybe you'll be there in gold" },
      { bar: 40, text: "Don't you haunt me kindly" },
      { bar: 42, text: "Haunt me true" },
      { bar: 44, text: "City of ghosts" },
      { bar: 46, text: "I'm still walking you" },
    ],
  },
  {
    id: "one-last-dance",
    no: 9,
    title: "One Last Dance",
    bpm: 118,
    bars: 48,
    tonic: 53,
    scale: "major",
    energy: 0.7,
    brightness: 0.72,
    swing: 0.1,
    mood: "pulse",
    theme: "orbit",
    cover: "/covers/09.jpg",
    verseChords: [0, 4, 5, 3],
    chorusChords: [0, 5, 3, 4],
    verseHook: [4, 4, 2, 0, 5, 5, 4, 2, 0, REST, 2, 4, 5, 4, 0, REST],
    chorusHook: [4, 5, 7, 7, 4, 2, 0, REST, 5, 5, 4, 2, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "Put your troubles on the coat rack" },
      { bar: 6, text: "Let the band play something slow" },
      { bar: 8, text: "If the night is almost over" },
      { bar: 10, text: "We can still refuse to go" },
      { bar: 12, text: "One more turn around the room" },
      { bar: 14, text: "One more lie that feels like luck" },
      { bar: 16, text: "Give me one last dance" },
      { bar: 18, text: "Before the lights come up" },
      { bar: 20, text: "If the morning wants the story" },
      { bar: 22, text: "We can tell it as a rush" },
      { bar: 24, text: "Your hand is a little reckless" },
      { bar: 26, text: "My timing's a little late" },
      { bar: 28, text: "Still the floor remembers both of us" },
      { bar: 30, text: "Like the song could change our fate" },
      { bar: 32, text: "Give me one last dance" },
      { bar: 34, text: "Before the lights come up" },
      { bar: 36, text: "If the morning wants the story" },
      { bar: 38, text: "We can tell it as a rush" },
      { bar: 40, text: "Don't let go, don't let go" },
      { bar: 42, text: "Count to four and spin me slow" },
      { bar: 44, text: "One last dance" },
      { bar: 46, text: "Then we go" },
    ],
  },
  {
    id: "electric-silence",
    no: 10,
    title: "Electric Silence",
    bpm: 108,
    bars: 48,
    tonic: 47,
    scale: "minor",
    energy: 0.5,
    brightness: 0.38,
    swing: 0.0,
    mood: "cold",
    theme: "scan",
    cover: "/covers/10.jpg",
    verseChords: [0, 6, 3, 5],
    chorusChords: [0, 4, 6, 3],
    verseHook: [0, REST, REST, 3, 5, REST, 3, 0, 2, REST, 3, 5, 7, 5, 3, REST],
    chorusHook: [7, REST, 5, 4, 7, REST, 4, 0, 3, 3, 2, 0, 5, 4, 0, REST],
    lyrics: [
      { bar: 4, text: "The room is full of unsaid voltage" },
      { bar: 6, text: "Your phone face-down like a blade" },
      { bar: 8, text: "I can hear the almost-sorry" },
      { bar: 10, text: "In the way you look away" },
      { bar: 12, text: "We could talk, we could break it" },
      { bar: 14, text: "We just let the quiet hum" },
      { bar: 16, text: "Electric silence" },
      { bar: 18, text: "Louder than a fight" },
      { bar: 20, text: "If you want me, say it" },
      { bar: 22, text: "Don't just fill the night" },
      { bar: 24, text: "Sparks along the kitchen counter" },
      { bar: 26, text: "Nothing moving but the clock" },
      { bar: 28, text: "I would take a broken sentence" },
      { bar: 30, text: "Over living in the static" },
      { bar: 32, text: "Electric silence" },
      { bar: 34, text: "Louder than a fight" },
      { bar: 36, text: "If you want me, say it" },
      { bar: 38, text: "Don't just fill the night" },
      { bar: 40, text: "Speak, or let me go" },
      { bar: 42, text: "I can't hold a ghost that won't" },
      { bar: 44, text: "Electric silence" },
      { bar: 46, text: "Cut the wire" },
    ],
  },
  {
    id: "paper-crown",
    no: 11,
    title: "Paper Crown",
    bpm: 100,
    bars: 48,
    tonic: 45,
    scale: "minor",
    energy: 0.45,
    brightness: 0.5,
    swing: 0.04,
    mood: "haze",
    theme: "shatter",
    cover: "/covers/11.jpg",
    verseChords: [0, 3, 4, 5],
    chorusChords: [5, 0, 3, 4],
    verseHook: [3, 2, 0, REST, 4, 3, 2, 0, 5, 4, 2, REST, 0, 2, 0, REST],
    chorusHook: [7, 5, 4, 0, 7, 5, 3, 0, 4, 4, 2, 0, 5, 3, 0, REST],
    lyrics: [
      { bar: 4, text: "They dressed me up in borrowed glory" },
      { bar: 6, text: "Told me I was made of more" },
      { bar: 8, text: "But a kingdom built of paper" },
      { bar: 10, text: "Folds the second it gets warm" },
      { bar: 12, text: "I smile like I was chosen" },
      { bar: 14, text: "I shake like I was found" },
      { bar: 16, text: "I wear a paper crown" },
      { bar: 18, text: "Don't you look too close" },
      { bar: 20, text: "If the rain comes down" },
      { bar: 22, text: "I'll be nobody you know" },
      { bar: 24, text: "Applause is just a weather" },
      { bar: 26, text: "It moves, it never stays" },
      { bar: 28, text: "I keep a spare identity" },
      { bar: 30, text: "In the lining of my name" },
      { bar: 32, text: "I wear a paper crown" },
      { bar: 34, text: "Don't you look too close" },
      { bar: 36, text: "If the rain comes down" },
      { bar: 38, text: "I'll be nobody you know" },
      { bar: 40, text: "Let it wrinkle, let it tear" },
      { bar: 42, text: "I was never the heir" },
      { bar: 44, text: "Paper crown" },
      { bar: 46, text: "I'm still here" },
    ],
  },
  {
    id: "until-morning",
    no: 12,
    title: "Until Morning",
    bpm: 92,
    bars: 48,
    tonic: 52,
    scale: "dorian",
    energy: 0.38,
    brightness: 0.44,
    swing: 0.07,
    mood: "night",
    theme: "haze",
    cover: "/covers/12.jpg",
    verseChords: [0, 4, 3, 5],
    chorusChords: [0, 5, 3, 4],
    verseHook: [4, REST, 2, 0, 5, REST, 4, 2, 0, REST, 2, 4, 5, 4, 2, REST],
    chorusHook: [5, 5, 4, 2, 0, REST, 4, 5, 7, 5, 4, 2, 0, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "Don't you start the car yet" },
      { bar: 6, text: "The sky is still deciding" },
      { bar: 8, text: "We can steal another hour" },
      { bar: 10, text: "From the thing called daylight" },
      { bar: 12, text: "Talk in almost-whispers" },
      { bar: 14, text: "Like the walls are on our side" },
      { bar: 16, text: "Stay until morning" },
      { bar: 18, text: "Let the dark do what it does" },
      { bar: 20, text: "If the sun wants a confession" },
      { bar: 22, text: "We'll be gone before it comes" },
      { bar: 24, text: "Your pulse against my shoulder" },
      { bar: 26, text: "A clock that lost the will" },
      { bar: 28, text: "I would trade a hundred daytimes" },
      { bar: 30, text: "For a night that wants us still" },
      { bar: 32, text: "Stay until morning" },
      { bar: 34, text: "Let the dark do what it does" },
      { bar: 36, text: "If the sun wants a confession" },
      { bar: 38, text: "We'll be gone before it comes" },
      { bar: 40, text: "One more song, one more window" },
      { bar: 42, text: "Hold the blue hour down" },
      { bar: 44, text: "Until morning" },
      { bar: 46, text: "Stay somehow" },
    ],
  },
  {
    id: "hurt-like-heaven",
    no: 13,
    title: "Hurt Like Heaven",
    bpm: 122,
    bars: 52,
    tonic: 48,
    scale: "minor",
    energy: 0.8,
    brightness: 0.52,
    swing: 0.0,
    mood: "ember",
    theme: "bloom",
    cover: "/covers/13.jpg",
    verseChords: [0, 6, 3, 4],
    chorusChords: [5, 3, 0, 4],
    verseHook: [0, 0, 3, 5, 7, REST, 5, 3, 0, 2, 3, 5, 4, 4, 2, REST],
    chorusHook: [7, 7, 5, 4, 7, 7, 4, 0, 5, 5, 3, 0, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "You loved me like a landslide" },
      { bar: 6, text: "Beautiful and much too fast" },
      { bar: 8, text: "I still taste the almost-holy" },
      { bar: 10, text: "In a wound that learned to last" },
      { bar: 12, text: "If this is what the fall is" },
      { bar: 14, text: "I would take it all again" },
      { bar: 16, text: "You hurt like heaven" },
      { bar: 18, text: "You leave like light" },
      { bar: 20, text: "I keep the bruise because it" },
      { bar: 22, text: "Proves I was alive" },
      { bar: 24, text: "Choir of the 3 a.m. traffic" },
      { bar: 26, text: "Stained glass in a liquor sign" },
      { bar: 28, text: "I got down on nothing's altar" },
      { bar: 30, text: "And I swore you were divine" },
      { bar: 32, text: "You hurt like heaven" },
      { bar: 34, text: "You leave like light" },
      { bar: 36, text: "I keep the bruise because it" },
      { bar: 38, text: "Proves I was alive" },
      { bar: 40, text: "Amen, amen, I still want it" },
      { bar: 42, text: "Even when it splits the sky" },
      { bar: 44, text: "You hurt like heaven" },
      { bar: 46, text: "Don't you dare be kind" },
      { bar: 48, text: "Hurt like heaven" },
      { bar: 50, text: "Stay in my mind" },
    ],
  },
  {
    id: "static-kiss",
    no: 14,
    title: "Static Kiss",
    bpm: 98,
    bars: 48,
    tonic: 54,
    scale: "minor",
    energy: 0.42,
    brightness: 0.4,
    swing: 0.05,
    mood: "cold",
    theme: "scan",
    cover: "/covers/14.jpg",
    verseChords: [0, 5, 3, 4],
    chorusChords: [3, 0, 5, 4],
    verseHook: [2, REST, 0, 2, 3, REST, 5, 3, 2, REST, 0, 2, 4, 2, 0, REST],
    chorusHook: [5, 5, 4, 2, 0, REST, 3, 5, 7, 5, 3, 0, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "A thousand miles of bad connection" },
      { bar: 6, text: "Your laugh arrives in broken lace" },
      { bar: 8, text: "I close my eyes and try to kiss you" },
      { bar: 10, text: "Through a glitch across your face" },
      { bar: 12, text: "Love in low resolution" },
      { bar: 14, text: "Still I lean into the hiss" },
      { bar: 16, text: "Give me a static kiss" },
      { bar: 18, text: "Even if it doesn't land" },
      { bar: 20, text: "I'd rather have the interference" },
      { bar: 22, text: "Than an empty quiet hand" },
      { bar: 24, text: "We hang up just to call back" },
      { bar: 26, text: "Like the night might change its mind" },
      { bar: 28, text: "I wear your voice like a jacket" },
      { bar: 30, text: "Two sizes too unkind" },
      { bar: 32, text: "Give me a static kiss" },
      { bar: 34, text: "Even if it doesn't land" },
      { bar: 36, text: "I'd rather have the interference" },
      { bar: 38, text: "Than an empty quiet hand" },
      { bar: 40, text: "Stay on the line, stay on the line" },
      { bar: 42, text: "Pixel mouth, still mine" },
      { bar: 44, text: "Static kiss" },
      { bar: 46, text: "One more time" },
    ],
  },
  {
    id: "no-angels",
    no: 15,
    title: "No Angels",
    bpm: 128,
    bars: 48,
    tonic: 55,
    scale: "minor",
    energy: 0.92,
    brightness: 0.55,
    swing: 0.0,
    mood: "pulse",
    theme: "grid",
    cover: "/covers/15.jpg",
    verseChords: [0, 6, 4, 5],
    chorusChords: [0, 3, 6, 4],
    verseHook: [0, 0, 3, 5, 7, 7, 5, 0, 4, 4, 2, 0, 5, 4, 0, REST],
    chorusHook: [7, 7, 7, 4, 0, 0, 4, 5, 7, 5, 4, 0, 7, 4, 0, REST],
    lyrics: [
      { bar: 4, text: "Don't send a rescue, I didn't ask" },
      { bar: 6, text: "I like the trouble I can name" },
      { bar: 8, text: "Halo's just a cheap accessory" },
      { bar: 10, text: "On a face that wants the flame" },
      { bar: 12, text: "We don't need a higher power" },
      { bar: 14, text: "We need a darker song" },
      { bar: 16, text: "No angels here" },
      { bar: 18, text: "No one coming down" },
      { bar: 20, text: "We save ourselves" },
      { bar: 22, text: "Or we burn the town" },
      { bar: 24, text: "Kiss me like a warning" },
      { bar: 26, text: "Dance me like a crime" },
      { bar: 28, text: "If heaven had a guest list" },
      { bar: 30, text: "We were never the right kind" },
      { bar: 32, text: "No angels here" },
      { bar: 34, text: "No one coming down" },
      { bar: 36, text: "We save ourselves" },
      { bar: 38, text: "Or we burn the town" },
      { bar: 40, text: "Let the choir take a night off" },
      { bar: 42, text: "We'll be loud enough" },
      { bar: 44, text: "No angels" },
      { bar: 46, text: "That's the stuff" },
    ],
  },
  {
    id: "fade-with-me",
    no: 16,
    title: "Fade With Me",
    bpm: 88,
    bars: 44,
    tonic: 50,
    scale: "minor",
    energy: 0.3,
    brightness: 0.36,
    swing: 0.06,
    mood: "haze",
    theme: "haze",
    cover: "/covers/16.jpg",
    verseChords: [0, 5, 3, 4],
    chorusChords: [5, 4, 0, 3],
    verseHook: [4, REST, 2, 0, REST, REST, 2, 3, 4, REST, 5, 3, 2, 0, REST, REST],
    chorusHook: [7, REST, 5, 4, 2, REST, 0, 2, 4, 4, 2, 0, 5, 3, 0, REST],
    lyrics: [
      { bar: 4, text: "Colors leaving at the edges" },
      { bar: 6, text: "Your outline going soft" },
      { bar: 8, text: "I don't want a brighter future" },
      { bar: 10, text: "I want the dim we started from" },
      { bar: 12, text: "If the world is going quiet" },
      { bar: 14, text: "Let it take us as a pair" },
      { bar: 16, text: "Fade with me" },
      { bar: 18, text: "Don't you stay in focus" },
      { bar: 20, text: "If we blur, we still belong" },
      { bar: 22, text: "To the almost, to the hush" },
      { bar: 24, text: "Photographs forget their faces" },
      { bar: 26, text: "Songs forget the key" },
      { bar: 28, text: "I will not be left in high-def" },
      { bar: 30, text: "While you dissolve from me" },
      { bar: 32, text: "Fade with me" },
      { bar: 34, text: "Don't you stay in focus" },
      { bar: 36, text: "If we blur, we still belong" },
      { bar: 38, text: "To the almost, to the hush" },
      { bar: 40, text: "Slow, slow, let it go" },
      { bar: 42, text: "Fade with me, I know" },
    ],
  },
  {
    id: "wildfire-eyes",
    no: 17,
    title: "Wildfire Eyes",
    bpm: 120,
    bars: 48,
    tonic: 45,
    scale: "dorian",
    energy: 0.78,
    brightness: 0.64,
    swing: 0.02,
    mood: "ember",
    theme: "bloom",
    cover: "/covers/17.jpg",
    verseChords: [0, 4, 6, 3],
    chorusChords: [0, 3, 5, 4],
    verseHook: [0, 2, 4, 5, 7, REST, 5, 4, 0, 0, 2, 4, 5, 4, 2, REST],
    chorusHook: [7, 5, 4, 2, 7, 5, 4, 0, 4, 4, 2, 0, 5, 4, 0, REST],
    lyrics: [
      { bar: 4, text: "You walked in like July in winter" },
      { bar: 6, text: "Every head forgot the cold" },
      { bar: 8, text: "I should've looked a little lower" },
      { bar: 10, text: "But your gaze was taking hold" },
      { bar: 12, text: "Warning signs in every language" },
      { bar: 14, text: "I was never good at those" },
      { bar: 16, text: "Wildfire eyes" },
      { bar: 18, text: "You can have the room" },
      { bar: 20, text: "If I burn a little later" },
      { bar: 22, text: "At least I saw the truth" },
      { bar: 24, text: "Spark along the collarbone" },
      { bar: 26, text: "Smoke behind a smile" },
      { bar: 28, text: "I would rather lose the evening" },
      { bar: 30, text: "Than be careful for a while" },
      { bar: 32, text: "Wildfire eyes" },
      { bar: 34, text: "You can have the room" },
      { bar: 36, text: "If I burn a little later" },
      { bar: 38, text: "At least I saw the truth" },
      { bar: 40, text: "Don't you blink, don't you cool it" },
      { bar: 42, text: "Let the whole night catch" },
      { bar: 44, text: "Wildfire eyes" },
      { bar: 46, text: "That's a match" },
    ],
  },
  {
    id: "last-goodbye",
    no: 18,
    title: "Last Goodbye",
    bpm: 86,
    bars: 44,
    tonic: 48,
    scale: "minor",
    energy: 0.32,
    brightness: 0.4,
    swing: 0.04,
    mood: "haze",
    theme: "orbit",
    cover: "/covers/18.jpg",
    verseChords: [0, 5, 3, 4],
    chorusChords: [5, 3, 0, 4],
    verseHook: [4, REST, 2, 0, REST, 3, 2, 0, 5, REST, 4, 2, 0, 2, 0, REST],
    chorusHook: [7, 5, 4, 0, 4, REST, 2, 0, 5, 5, 3, 0, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "We said it in the doorway" },
      { bar: 6, text: "Like a prayer we didn't mean" },
      { bar: 8, text: "Bags already by the elevator" },
      { bar: 10, text: "A life packed in between" },
      { bar: 12, text: "I wanted one more ordinary" },
      { bar: 14, text: "You wanted out of the scene" },
      { bar: 16, text: "This is the last goodbye" },
      { bar: 18, text: "I won't dress it up as later" },
      { bar: 20, text: "If I see you in another life" },
      { bar: 22, text: "We'll be kinder, maybe braver" },
      { bar: 24, text: "Leave the key, leave the record" },
      { bar: 26, text: "Leave the plant I never named" },
      { bar: 28, text: "I will water what you planted" },
      { bar: 30, text: "Till the leaving feels like rain" },
      { bar: 32, text: "This is the last goodbye" },
      { bar: 34, text: "I won't dress it up as later" },
      { bar: 36, text: "If I see you in another life" },
      { bar: 38, text: "We'll be kinder, maybe braver" },
      { bar: 40, text: "Go on, I'll be still" },
      { bar: 42, text: "Last goodbye, I will" },
    ],
  },
  {
    id: "forever-tonight",
    no: 19,
    title: "Forever Tonight",
    bpm: 114,
    bars: 48,
    tonic: 53,
    scale: "minor",
    energy: 0.65,
    brightness: 0.56,
    swing: 0.03,
    mood: "ember",
    theme: "pulse",
    cover: "/covers/19.jpg",
    verseChords: [0, 4, 5, 3],
    chorusChords: [5, 0, 3, 4],
    verseHook: [0, 2, 4, REST, 5, 4, 2, 0, 3, 3, 2, REST, 0, 2, 0, REST],
    chorusHook: [4, 5, 7, 7, 4, 2, 0, REST, 5, 5, 3, 0, 4, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "We don't get a hundred summers" },
      { bar: 6, text: "We get a room and a cheap wine" },
      { bar: 8, text: "So I make a vow in present tense" },
      { bar: 10, text: "And I mean it for the night" },
      { bar: 12, text: "Tomorrow can go begging" },
      { bar: 14, text: "The future can wait outside" },
      { bar: 16, text: "Forever tonight" },
      { bar: 18, text: "That's the only time I trust" },
      { bar: 20, text: "If the clock tries to divide us" },
      { bar: 22, text: "We can teach it not to rush" },
      { bar: 24, text: "Your laugh is a small cathedral" },
      { bar: 26, text: "I get religion when you stay" },
      { bar: 28, text: "I don't need a marble promise" },
      { bar: 30, text: "I need you not to look away" },
      { bar: 32, text: "Forever tonight" },
      { bar: 34, text: "That's the only time I trust" },
      { bar: 36, text: "If the clock tries to divide us" },
      { bar: 38, text: "We can teach it not to rush" },
      { bar: 40, text: "Say it now, say it now" },
      { bar: 42, text: "While the dark allows" },
      { bar: 44, text: "Forever tonight" },
      { bar: 46, text: "That's enough" },
    ],
  },
  {
    id: "gold-in-the-dark",
    no: 20,
    title: "Gold in the Dark",
    bpm: 108,
    bars: 52,
    tonic: 52,
    scale: "major",
    energy: 0.6,
    brightness: 0.68,
    swing: 0.04,
    mood: "pulse",
    theme: "bloom",
    cover: "/covers/20.jpg",
    verseChords: [0, 4, 5, 3],
    chorusChords: [5, 3, 0, 4],
    verseHook: [0, REST, 2, 4, 5, REST, 4, 2, 0, REST, 4, 5, 7, 5, 4, REST],
    chorusHook: [4, 4, 5, 7, 4, 2, 0, REST, 5, 5, 4, 2, 0, 2, 0, REST],
    lyrics: [
      { bar: 4, text: "After all the neon and the leaving" },
      { bar: 6, text: "After all the almost-love" },
      { bar: 8, text: "There's a quiet in the wreckage" },
      { bar: 10, text: "That still knows what I was made of" },
      { bar: 12, text: "I don't need the sky to open" },
      { bar: 14, text: "I just need a little spark" },
      { bar: 16, text: "There's gold in the dark" },
      { bar: 18, text: "If you look without the fear" },
      { bar: 20, text: "Every night I thought would end me" },
      { bar: 22, text: "Left a vein of something here" },
      { bar: 24, text: "I pick the light out of the ashes" },
      { bar: 26, text: "I wear it like a thread" },
      { bar: 28, text: "Not a triumph, not a sermon" },
      { bar: 30, text: "Just a reason I'm not dead" },
      { bar: 32, text: "There's gold in the dark" },
      { bar: 34, text: "If you look without the fear" },
      { bar: 36, text: "Every night I thought would end me" },
      { bar: 38, text: "Left a vein of something here" },
      { bar: 40, text: "Afterglow, after all" },
      { bar: 42, text: "I am still a song" },
      { bar: 44, text: "Gold in the dark" },
      { bar: 46, text: "Carry on" },
      { bar: 48, text: "Gold in the dark" },
      { bar: 50, text: "Carry on" },
    ],
  },
];

export function songById(id: string) {
  return SONGS.find((s) => s.id === id);
}

export function padNo(n: number) {
  return n.toString().padStart(2, "0");
}

export function songClip(song: Song) {
  return `/videos/${padNo(song.no)}.mp4`;
}

export function songStill(song: Song) {
  return `/stills/${padNo(song.no)}.jpg`;
}

export function songDuration(song: Song) {
  return (song.bars * 4 * 60) / song.bpm;
}

export function albumDuration() {
  return SONGS.reduce((sum, s) => sum + songDuration(s), 0);
}

export function sectionAt(bar: number, bars: number): Section {
  if (bar < 4) return "intro";
  if (bar < 12) return "verse";
  if (bar < 16) return "pre";
  if (bar < 24) return "chorus";
  if (bar < 32) return "verse";
  if (bar < 40) return "chorus";
  if (bar < Math.min(44, bars)) return "bridge";
  if (bar >= bars - 4) return "outro";
  return "chorus";
}

export function lyricAt(song: Song, bar: number) {
  let current: LyricLine | undefined;
  for (const line of song.lyrics) {
    if (line.bar <= bar) current = line;
    else break;
  }
  return current;
}

export const PLATFORMS = [
  { id: "official", name: "LINNEIRO Official", status: "Playing now" },
  { id: "spotify", name: "Spotify", status: "Needs DistroKid" },
  { id: "apple", name: "Apple Music", status: "Needs DistroKid" },
  { id: "youtube", name: "YouTube Music", status: "Needs DistroKid" },
  { id: "amazon", name: "Amazon Music", status: "Needs DistroKid" },
  { id: "deezer", name: "Deezer", status: "Needs DistroKid" },
] as const;
