/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CopyRouteImport } from './routes/copy'
import { Route as MusicRouteImport } from './routes/music'
import { Route as Pack1RouteImport } from './routes/pack-1'
import { Route as Pack2RouteImport } from './routes/pack-2'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as WatchIdRouteImport } from './routes/watch.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CopyRoute = CopyRouteImport.update({
  id: '/copy',
  path: '/copy',
  getParentRoute: () => rootRouteImport,
} as any)
const MusicRoute = MusicRouteImport.update({
  id: '/music',
  path: '/music',
  getParentRoute: () => rootRouteImport,
} as any)
const Pack1Route = Pack1RouteImport.update({
  id: '/pack-1',
  path: '/pack-1',
  getParentRoute: () => rootRouteImport,
} as any)
const Pack2Route = Pack2RouteImport.update({
  id: '/pack-2',
  path: '/pack-2',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/copy': typeof CopyRoute
  '/music': typeof MusicRoute
  '/pack-1': typeof Pack1Route
  '/pack-2': typeof Pack2Route
  '/videos': typeof VideosRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/copy': typeof CopyRoute
  '/music': typeof MusicRoute
  '/pack-1': typeof Pack1Route
  '/pack-2': typeof Pack2Route
  '/videos': typeof VideosRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/copy': typeof CopyRoute
  '/music': typeof MusicRoute
  '/pack-1': typeof Pack1Route
  '/pack-2': typeof Pack2Route
  '/videos': typeof VideosRoute
  '/watch/$id': typeof WatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/copy' | '/music' | '/pack-1' | '/pack-2' | '/videos' | '/watch/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/copy' | '/music' | '/pack-1' | '/pack-2' | '/videos' | '/watch/$id'
  id:
    | '__root__'
    | '/'
    | '/copy'
    | '/music'
    | '/pack-1'
    | '/pack-2'
    | '/videos'
    | '/watch/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CopyRoute: typeof CopyRoute
  MusicRoute: typeof MusicRoute
  Pack1Route: typeof Pack1Route
  Pack2Route: typeof Pack2Route
  VideosRoute: typeof VideosRoute
  WatchIdRoute: typeof WatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/copy': {
      id: '/copy'
      path: '/copy'
      fullPath: '/copy'
      preLoaderRoute: typeof CopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/music': {
      id: '/music'
      path: '/music'
      fullPath: '/music'
      preLoaderRoute: typeof MusicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack-1': {
      id: '/pack-1'
      path: '/pack-1'
      fullPath: '/pack-1'
      preLoaderRoute: typeof Pack1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pack-2': {
      id: '/pack-2'
      path: '/pack-2'
      fullPath: '/pack-2'
      preLoaderRoute: typeof Pack2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CopyRoute: CopyRoute,
  MusicRoute: MusicRoute,
  Pack1Route: Pack1Route,
  Pack2Route: Pack2Route,
  VideosRoute: VideosRoute,
  WatchIdRoute: WatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
